server:
  port: 9093
  
spring:
  application:
    name: documentation-application    
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 40.85.215.6
      port: 8500
      
swagger: 
  config: 
    refreshrate: 5000      